basePath: /
definitions:
  service.School:
    properties:
      adminStandardCode:
        type: string
      id:
        type: integer
      roadAddress:
        type: string
      roadDetailAddress:
        type: string
      schoolName:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 희그 그 이후 API
  title: AfterHee API
  version: "1.0"
paths:
  /api/v1/schools:
    get:
      consumes:
      - application/json
      description: 학교 목록을 키워드를 바탕으로 조회한다
      parameters:
      - description: 검색 키워드
        in: query
        name: keyword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.School'
            type: array
      summary: 학교 목록 조회
swagger: "2.0"
